diff --git a/src/.autoconf/Makefile.in b/src/.autoconf/Makefile.in
index 0eeebc6..6cdff4f 100644
--- a/src/.autoconf/Makefile.in
+++ b/src/.autoconf/Makefile.in
@@ -34,7 +34,7 @@ INSTALL_BIN = @INSTALL_BIN@
 INSTALL_LIB = @INSTALL_LIB@
 OPENFST_CXXFLAGS = @OPENFST_CXXFLAGS@
 OPENFST_LDFLAGS  = @OPENFST_LDFLAGS@
-GIT_REVISION := $(shell git describe --abbrev=6 --dirty --always --tags)
+GIT_REVISION := $(COMMIT)
 
 CXX = @CXX@
 
@@ -57,6 +57,7 @@ ifeq ($(UNAME), Linux)
 LIBS=-lfst -ldl -lm -lrt -fopenmp
 CXX += -std=c++0x -Wall -Wno-sign-compare -Wno-unused-local-typedefs
 CFLAGS += -D_GNUC_
+
 endif
 
 
@@ -68,7 +69,7 @@ CFLAGS += -O2
 THIRD_PARTIES_INCLUDE ?= -I3rdparty/utfcpp \
 	-I3rdparty/rnnlm -I$(OPENFST_CXXFLAGS)
 
-EXTRA := $(CFLAGS) $(THIRD_PARTIES_INCLUDE) $(CXXFLAGS) $(CPPFLAGS)
+EXTRA := $(CFLAGS) $(THIRD_PARTIES_INCLUDE) $(CXXFLAGS) $(CPPFLAGS) $(LDFLAGS) -Wl,-rpath,$(FSTROOT)/lib
 OBJS  := $(LIBDIR)/util.o \
 	$(LIBDIR)/rnnlmlib.o \
 	$(LIBDIR)/LatticePruner.o \
